### PR TITLE
Rest user search

### PR DESCRIPTION
**Pull request by dhaliwal23**

### CODE REVIEW

**Comment by sanjayalwani** [comment]
There is still relative positioning which is throwing the page out. Also the styling hasnt been updated for the new separate search pages. Please merge master into your branch and update.

`git checkout master`
`git pull`
`git checkout restUserSearch`
`git merge master`

**Comment by dhaliwal23** [comment]
I already did that I pulled master onto my branch and updated the search pages and the layout

**Comment by sanjayalwani** [comment]
My bad I was behind!

The extra padding is gone but the relative positioning still causes text to disappear at even slightly different screen sizes, I'm not asking for mobile support but I think it can be improved, similar issues with responsivity on the login pages.
Screen Shot 2020-08-06 at 6 12 48 PM


Can the search pages also be centred since we only have a single column of information? What are your thoughts?

**Comment by dhaliwal23** [comment]
Oh yea I think would look better with searches in the middle of the page I’ll change that. I’ll also try figuring out the positioning

**Review by mann-c — APPROVED** [review]

**Pull request merged**
